#!/usr/bin/env python3
"""Generate src/casefold_table.rs: Unicode full case folding (statuses C and F).

The quote check (ASG-Q3) folds case as the manager's ruling says: NFKC, then
casefold. Rust's std has no full case folding (char::to_lowercase is a
different mapping: it keeps U+00DF, where folding gives "ss"), and no crate in
Cargo.lock provides it, so the table is generated from the Unicode data file.

    python3 gen_casefold_table.py [/usr/share/unicode/CaseFolding.txt]

Before writing, the parsed table is compared with Python's str.casefold() for
every code point, when Python's Unicode version matches the file's.
"""
import hashlib
import sys
import unicodedata

src = sys.argv[1] if len(sys.argv) > 1 else "/usr/share/unicode/CaseFolding.txt"
raw = open(src, "rb").read()
first = raw.decode("utf-8").splitlines()[0]          # "# CaseFolding-16.0.0.txt"
version = first.strip("# ").removeprefix("CaseFolding-").removesuffix(".txt")

table = {}
for line in raw.decode("utf-8").splitlines():
    line = line.split("#", 1)[0].strip()
    if not line:
        continue
    code, status, mapping = [f.strip() for f in line.split(";")[:3]]
    if status in ("C", "F"):
        table[int(code, 16)] = "".join(chr(int(h, 16)) for h in mapping.split())

checked = "not compared (Python has Unicode %s)" % unicodedata.unidata_version
if unicodedata.unidata_version == version:
    bad = 0
    for cp in range(0x110000):
        if 0xD800 <= cp <= 0xDFFF:
            continue
        c = chr(cp)
        if c.casefold() != table.get(cp, c):
            bad += 1
    if bad:
        sys.exit(f"{bad} code points disagree with str.casefold(); not writing")
    checked = "identical to Python str.casefold() for every code point"

def esc(s):
    return "".join("\\u{%x}" % ord(ch) for ch in s)

out = [
    "// @generated by gen_casefold_table.py -- do not edit by hand.",
    f"// Source: CaseFolding-{version}.txt, statuses C and F (full case folding).",
    f"// sha256 {hashlib.sha256(raw).hexdigest()}",
    f"// Check: {checked}.",
    "",
    "/// The Unicode version of the case-folding data below.",
    f"pub(crate) const UNICODE_VERSION: &str = \"{version}\";",
    "/// (code point, its full case folding), sorted by code point.",
    "pub(crate) const CASEFOLD: &[(char, &str)] = &[",
]
out += [f"    ('{esc(chr(cp))}', \"{esc(table[cp])}\")," for cp in sorted(table)]
out += ["];", ""]
open("src/casefold_table.rs", "w", encoding="ascii").write("\n".join(out))
print(f"wrote {len(table)} mappings from CaseFolding-{version}; {checked}")
